### PR TITLE
Extract correct JAVA_HOME from custom URLs

### LINKED ISSUE #631: AdoptOpenJDK install doesn't handle JAVA_HOME correctly
### :speaking_head: Foreword

When using the adoptopenjdk_install resource it fails to honor the java_home property correctly.

## :ghost: Brief Description

Installing adoptopenjdk 8 with the default java_home settings leads to $JAVA_HOME being set to "/usr/lib/jvm/java-8-adoptopenjdk-hotspot/chef" which is a directory that doesn't exist. The installation actually resides in "/usr/lib/jvm/java-8-adoptopenjdk-hotspot/jdk8u232-b09".

Setting the java_home property in the resource to e.g. "/usr/lib/jvm/default-java" sets $JAVA_HOME to said path but doesn't actually install java there or create a symlink to the installation directory, which happens to be "/usr/lib/jvm/jdk8u232-b09" in that case.

## :pancakes: Cookbook version

java 8.3.0

## :woman_cook:  Chef-Infra Version

chef 16.3.38

## :tophat: Platform details

CentOS 7

## Steps To Reproduce

1. Try to use adoptopenjdk_install to install java 8. Don't set anything for java_home
2. Log in to the machine and see that $JAVA_HOME is set incorrectly and that the shell can't find the java binary as a result.

Alternatively:

1. Try to use adoptopenjdk_install to install java 8. Set java_home to e.g. /usr/lib/jvm/default-java.
2. Log in to the machine and see that $JAVA_HOME is set correctly but the specified directory doesn't exist.

## :police_car: Expected behavior

My expectation would be that java is either installed to java_home or that a symlink is created to the install directory.

### PR DESCRIPTION
**Pull request by detjensrobert**
### Description

This fixes the logic that pulls the `JAVA_HOME` envvar from the install url. Previously this only worked for the default AdoptOpenJDK Github release urls. 

### Issues Resolved
Fixes #631.

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by ramereth** [comment]
@detjensrobert you might want to see if happens with the other JDK's we support in this cookbook and fix if needed.

**Comment by detjensrobert** [comment]
The other JDKs set the home based on the version number, not the download link. They don't appear to be affected since the version number is set separately when using a custom URL.

**Comment by bkonick** [comment]
@detjensrobert I just tried this out and it worked for AdoptOpenJDK 8 but not 11.

**Comment by bkonick** [comment]
Here's the output of that split:

```
irb(main):001:0> url = 'OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz'
irb(main):002:0> url.split('/')[-1].split('.')[0].split('_')[-1]
=> "11"
irb(main):003:0> url = 'OpenJDK8U-jdk_x64_linux_hotspot_8u265b01.tar.gz'
irb(main):004:0> url.split('/')[-1].split('.')[0].split('_')[-1]
=> "8u265b01"
```

**Comment by detjensrobert** [comment]
@bkonick What does the filename for 11 look like? `OpenJDK11U-jdk_x64_linux_hotspot_11u###b##.tar.gz`? I think I know what the problem is with how I handle the filename.

**Comment by detjensrobert** [comment]
@bkonick I've updated the logic and it should work for newer versions. Please try it again!

**Comment by bkonick** [comment]
Thanks, @detjensrobert! This worked on both 8 and 11 for me. 🎉  

Just a heads up that we don't use other variants (openj9 or openj9 large heap) so I haven't tested those.

File: libraries/adopt_openjdk_helpers.rb [hunk 1]
```diff
@@ -22,14 +22,19 @@ def sub_dir(url)
...
 
-          raise("Failed to parse #{f} for directory name!") if hash.empty?
+          # Get version number from start of filename
+          case (basename.scan /\d+/)[0]
+          when '8'
+            ver = basename.split('_')[-1]
+            "jdk#{ver[0..4]}-#{ver[-3..-1]}"
+          else
+            ver = basename.split('_')
+            "jdk-#{ver[-2]}+#{ver[-1]}"
```
Comment (bkonick) [inline libraries/adopt_openjdk_helpers.rb:35]: I was just playing around in irb and this line should support both hotspot and openj9 if rewritten as:

```ruby
"jdk-#{ver[4]}+#{ver[5]}"
```

File: libraries/adopt_openjdk_helpers.rb [hunk 2]
```diff
@@ -22,14 +22,19 @@ def sub_dir(url)
...
-          # get file basename, remove extention, get hash
-          hash = url.split('/')[-1].split('.')[0].split('_')[-1]
+          # get file basename without extension
+          basename = url.split('/')[-1].gsub('.tar.gz', '')
 
-          raise("Failed to parse #{f} for directory name!") if hash.empty?
+          # Get version number from start of filename
+          case (basename.scan /\d+/)[0]
+          when '8'
+            ver = basename.split('_')[-1]
```
Comment (bkonick) [inline libraries/adopt_openjdk_helpers.rb:31]: This won't support openj9 either. Changing to below should work:

```ruby
ver = basename.split('_')[4]
```

**Comment by bkonick** [comment]
@detjensrobert made a couple inline suggestions to support both openj9 and hotspot. It seems that openj9 large heap is not the same as regular openj9 so an additional check would be needed to account for that.

```
irb(main):003:0> basename.split('_')[4]
=> "linuxXL"
irb(main):004:0> basename.split('_')[5]
=> "11.0.8"
irb(main):005:0> basename.split('_')[6]
=> "10"
```

File: documentation/resources/adoptopenjdk_install.md [hunk 3]
```diff
@@ -33,17 +33,27 @@ Introduced: v7.0.0
...
 end
 ```
+
+To install AdoptOpenJDK 11 from a custom tarball:
+
+```ruby
+adoptopenjdk_install '11' do
+  variant 'hotspot'
+  url 'http://url.of/path/to/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz'
+  checksum asdfasdfasdf
```
Comment (ramereth) [inline documentation/resources/adoptopenjdk_install.md:57]:
```suggestion
  checksum 'asdfasdfasdf'
```

File: documentation/resources/adoptopenjdk_linux_install.md [hunk 4]
```diff
@@ -26,17 +26,27 @@ Introduced: v8.1.0
...
 end
 ```
+
+To install AdoptOpenJDK 11 from a custom tarball:
+
+```ruby
+adoptopenjdk_install '11' do
+  variant 'hotspot'
+  url 'http://url.of/path/to/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz'
+  checksum asdfasdfasdf
```
Comment (ramereth) [inline documentation/resources/adoptopenjdk_linux_install.md:50]:
```suggestion
  checksum 'asdfasdfasdf'
```

**Comment by detjensrobert** [comment]
The new logic I added also works for the default urls. Should I remove the old logic and just use the new one to simplify the helper?

**Comment by detjensrobert** [comment]
(failing test is a package install timeout, not related to my changes)

**Comment by ramereth** [comment]
> The new logic I added also works for the default urls. Should I remove the old logic and just use the new one to simplify the helper?

How do you mean exactly?

**Comment by detjensrobert** [comment]
@ramereth Since the new logic extracts the path from the filename and doesn't care about the URL path at all, it works for all files including the default Github release tarballs. Do we need to keep the old way of extracting the home dir from the Github URL path for the default URLs or can I remove the old logic and use the new logic I added for all URLs (including the defaults)?

**Comment by ramereth** [comment]
@detjensrobert as long as it works both ways I don't see a reason for keeping the old logic

File: libraries/adopt_openjdk_helpers.rb [hunk 5]
```diff
@@ -2,23 +2,30 @@ module Java
   module Cookbook
     module AdoptOpenJdkHelpers
       def sub_dir(url)
-        uri = URI.parse(url)
```
Comment (bkonick) [inline libraries/adopt_openjdk_helpers.rb:5]: Does it make sense to keep `URI.parse` to make sure the path provided is a valid URI? That way if someone mistakenly provided something like `foo\bar/bam.tar.gz` it would fail fast.

Comment (ramereth) [reply libraries/adopt_openjdk_helpers.rb:5]: Yeah, I think that'd be a great thing to keep at least.

**Comment by ramereth** [comment]
@tas50 @Xorima @bkonick can you please take another look?

**Comment by bkonick** [comment]
> @tas50 @Xorima @bkonick can you please take another look?

LGTM 👍

**Comment by ramereth** [comment]
Released as 8.3.1.
